default_config:

logger:
  default: info
  logs:
    custom_components.rivian: debug
    rivian: debug

# Uncomment to enable remote debugging (https://www.home-assistant.io/integrations/debugpy/)
# debugpy:
#   start: true
#   wait: false
